### PR TITLE
Move cached server to XDG-compliant location

### PR DESCRIPTION
**Pull request by milhnl**
Hey, I'm working on integrating this project into my workflow. This seems like a useful first step, as I like to keep my home directory clean. Please take a look at the "roslyn-language-server.github.com" url included in the commit. It's meant to be a project url.  I use my own domain for this most of the time, but I did not see a website on your GitHub profile, so this is just a suggestion. I think it is only used in url form on macOS.

### CODE REVIEW

**Comment by SofusA** [comment]
Thanks for working on this. This is great!

In `start_roslyn()` a log directory is located relative to the home directory. 
I think we should use the project directory here as well and remove the dependency to `home`

**Comment by SofusA** [comment]
It would make sense to find the project directory in `start_roslyn()` and add project directory as an argument to `ensure_roslyn_is_installed()`.

**Comment by milhnl** [comment]
Hi, thanks for the suggestions! I completely missed the log files. I couldn't resist make the path handling immutable, so the commit is a bit bigger than necessary. If you want me to split it, that's possible, but I thought you wouldn't care.

**Comment by SofusA** [comment]
This is nice :smiley: 

I really appreciate your work.

**Pull request merged**
